// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 947975424;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__ai__analyze_network_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_network",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok =
                            Result::<_, ()>::Ok(crate::api::ai::analyze_network().await)?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__ai__apply_optimization_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "apply_optimization",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_actions = <Vec<String>>::sse_decode(&mut deserializer);
            let api_before_ping = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::ai::apply_optimization(api_actions, api_before_ping).await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__engine__disable_pro_auto_optimize_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "disable_pro_auto_optimize",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::engine::disable_pro_auto_optimize();
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__enable_pro_auto_optimize_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "enable_pro_auto_optimize",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::engine::enable_pro_auto_optimize();
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__get_about_info_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_about_info",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::engine::get_about_info())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__ai__get_ai_advice_v2_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_ai_advice_v2",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_icmp_ping = <u32>::sse_decode(&mut deserializer);
            let api_tcp_ping = <u32>::sse_decode(&mut deserializer);
            let api_gateway_ping = <u32>::sse_decode(&mut deserializer);
            let api_gateway_ip = <String>::sse_decode(&mut deserializer);
            let api_jitter = <u32>::sse_decode(&mut deserializer);
            let api_packet_loss = <f32>::sse_decode(&mut deserializer);
            let api_dns_ms = <u32>::sse_decode(&mut deserializer);
            let api_dns_server = <String>::sse_decode(&mut deserializer);
            let api_wifi_signal = <u8>::sse_decode(&mut deserializer);
            let api_wifi_channel = <u16>::sse_decode(&mut deserializer);
            let api_wifi_band = <String>::sse_decode(&mut deserializer);
            let api_active_connections = <u32>::sse_decode(&mut deserializer);
            let api_adapter_speed = <u32>::sse_decode(&mut deserializer);
            let api_download = <f64>::sse_decode(&mut deserializer);
            let api_upload = <f64>::sse_decode(&mut deserializer);
            let api_background_apps = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::ai::get_ai_advice_v2(
                                api_icmp_ping,
                                api_tcp_ping,
                                api_gateway_ping,
                                api_gateway_ip,
                                api_jitter,
                                api_packet_loss,
                                api_dns_ms,
                                api_dns_server,
                                api_wifi_signal,
                                api_wifi_channel,
                                api_wifi_band,
                                api_active_connections,
                                api_adapter_speed,
                                api_download,
                                api_upload,
                                api_background_apps,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__ai__get_diagnostics_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_diagnostics",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_icmp_ping = <u32>::sse_decode(&mut deserializer);
            let api_tcp_ping = <u32>::sse_decode(&mut deserializer);
            let api_gateway_ping = <u32>::sse_decode(&mut deserializer);
            let api_gateway_ip = <String>::sse_decode(&mut deserializer);
            let api_jitter = <u32>::sse_decode(&mut deserializer);
            let api_packet_loss = <f32>::sse_decode(&mut deserializer);
            let api_dns_ms = <u32>::sse_decode(&mut deserializer);
            let api_dns_server = <String>::sse_decode(&mut deserializer);
            let api_wifi_signal = <u8>::sse_decode(&mut deserializer);
            let api_wifi_channel = <u16>::sse_decode(&mut deserializer);
            let api_wifi_band = <String>::sse_decode(&mut deserializer);
            let api_active_connections = <u32>::sse_decode(&mut deserializer);
            let api_adapter_speed = <u32>::sse_decode(&mut deserializer);
            let api_download = <f64>::sse_decode(&mut deserializer);
            let api_upload = <f64>::sse_decode(&mut deserializer);
            let api_background_apps = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::ai::get_diagnostics(
                                api_icmp_ping,
                                api_tcp_ping,
                                api_gateway_ping,
                                api_gateway_ip,
                                api_jitter,
                                api_packet_loss,
                                api_dns_ms,
                                api_dns_server,
                                api_wifi_signal,
                                api_wifi_channel,
                                api_wifi_band,
                                api_active_connections,
                                api_adapter_speed,
                                api_download,
                                api_upload,
                                api_background_apps,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__engine__get_v2_metrics_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_v2_metrics",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok =
                            Result::<_, ()>::Ok(crate::api::engine::get_v2_metrics().await)?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__engine__init_v2_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_v2",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::engine::init_v2();
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__ai__run_bufferbloat_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "run_bufferbloat",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_target = <String>::sse_decode(&mut deserializer);
            let api_url = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::ai::run_bufferbloat(api_target, api_url).await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__ai__run_traceroute_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "run_traceroute",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_target = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok =
                            Result::<_, ()>::Ok(crate::api::ai::run_traceroute(api_target).await)?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__ai__set_api_key_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_api_key",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_key = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::ai::set_api_key(api_key);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__start_adaptive_engine_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_adaptive_engine",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::engine::start_adaptive_engine();
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__stop_adaptive_engine_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_adaptive_engine",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::engine::stop_adaptive_engine();
                })?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::plugins::speedtest::BufferbloatResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_idlePingMs = <u32>::sse_decode(deserializer);
        let mut var_downloadPingMs = <u32>::sse_decode(deserializer);
        let mut var_uploadPingMs = <u32>::sse_decode(deserializer);
        let mut var_grade = <String>::sse_decode(deserializer);
        return crate::plugins::speedtest::BufferbloatResult {
            idle_ping_ms: var_idlePingMs,
            download_ping_ms: var_downloadPingMs,
            upload_ping_ms: var_uploadPingMs,
            grade: var_grade,
        };
    }
}

impl SseDecode for crate::plugins::ai::DiagnosticItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_severity = <String>::sse_decode(deserializer);
        let mut var_category = <String>::sse_decode(deserializer);
        let mut var_problem = <String>::sse_decode(deserializer);
        let mut var_reason = <String>::sse_decode(deserializer);
        let mut var_howChecked = <String>::sse_decode(deserializer);
        let mut var_solution = <String>::sse_decode(deserializer);
        let mut var_expectedResult = <String>::sse_decode(deserializer);
        let mut var_confidencePct = <u8>::sse_decode(deserializer);
        return crate::plugins::ai::DiagnosticItem {
            severity: var_severity,
            category: var_category,
            problem: var_problem,
            reason: var_reason,
            how_checked: var_howChecked,
            solution: var_solution,
            expected_result: var_expectedResult,
            confidence_pct: var_confidencePct,
        };
    }
}

impl SseDecode for crate::plugins::dns::DnsBenchmark {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_target = <String>::sse_decode(deserializer);
        let mut var_latencyMs = <u32>::sse_decode(deserializer);
        let mut var_reliabilityPct = <u8>::sse_decode(deserializer);
        return crate::plugins::dns::DnsBenchmark {
            target: var_target,
            latency_ms: var_latencyMs,
            reliability_pct: var_reliabilityPct,
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::plugins::traceroute::HopStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_hop = <u8>::sse_decode(deserializer);
        let mut var_ip = <String>::sse_decode(deserializer);
        let mut var_latencyMs = <u32>::sse_decode(deserializer);
        let mut var_isTimeout = <bool>::sse_decode(deserializer);
        return crate::plugins::traceroute::HopStatus {
            hop: var_hop,
            ip: var_ip,
            latency_ms: var_latencyMs,
            is_timeout: var_isTimeout,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::plugins::ai::DiagnosticItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::plugins::ai::DiagnosticItem>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::plugins::dns::DnsBenchmark> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::plugins::dns::DnsBenchmark>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::plugins::traceroute::HopStatus> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::plugins::traceroute::HopStatus>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::plugins::optimizer::OptimizationRecommendation> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(
                <crate::plugins::optimizer::OptimizationRecommendation>::sse_decode(deserializer),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::plugins::ping::PingStats> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::plugins::ping::PingStats>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::plugins::traffic::ProcessTraffic> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::plugins::traffic::ProcessTraffic>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Option<crate::plugins::wifi::WifiStats> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::plugins::wifi::WifiStats>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::plugins::optimizer::OptimizationRecommendation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_description = <String>::sse_decode(deserializer);
        let mut var_isRecommended = <bool>::sse_decode(deserializer);
        return crate::plugins::optimizer::OptimizationRecommendation {
            id: var_id,
            title: var_title,
            description: var_description,
            is_recommended: var_isRecommended,
        };
    }
}

impl SseDecode for crate::plugins::optimizer::OptimizationReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_beforePing = <u32>::sse_decode(deserializer);
        let mut var_afterPing = <u32>::sse_decode(deserializer);
        let mut var_pingDiff = <i32>::sse_decode(deserializer);
        let mut var_summary = <String>::sse_decode(deserializer);
        let mut var_actionsTaken = <Vec<String>>::sse_decode(deserializer);
        return crate::plugins::optimizer::OptimizationReport {
            before_ping: var_beforePing,
            after_ping: var_afterPing,
            ping_diff: var_pingDiff,
            summary: var_summary,
            actions_taken: var_actionsTaken,
        };
    }
}

impl SseDecode for crate::plugins::ping::PingStats {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_target = <String>::sse_decode(deserializer);
        let mut var_pingType = <String>::sse_decode(deserializer);
        let mut var_averageMs = <f32>::sse_decode(deserializer);
        let mut var_bestMs = <u32>::sse_decode(deserializer);
        let mut var_worstMs = <u32>::sse_decode(deserializer);
        let mut var_medianMs = <u32>::sse_decode(deserializer);
        let mut var_p95Ms = <u32>::sse_decode(deserializer);
        let mut var_jitterMs = <f32>::sse_decode(deserializer);
        let mut var_packetLossPct = <f32>::sse_decode(deserializer);
        return crate::plugins::ping::PingStats {
            target: var_target,
            ping_type: var_pingType,
            average_ms: var_averageMs,
            best_ms: var_bestMs,
            worst_ms: var_worstMs,
            median_ms: var_medianMs,
            p95_ms: var_p95Ms,
            jitter_ms: var_jitterMs,
            packet_loss_pct: var_packetLossPct,
        };
    }
}

impl SseDecode for crate::plugins::traffic::ProcessTraffic {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_pid = <u32>::sse_decode(deserializer);
        let mut var_memoryMb = <f64>::sse_decode(deserializer);
        return crate::plugins::traffic::ProcessTraffic {
            name: var_name,
            pid: var_pid,
            memory_mb: var_memoryMb,
        };
    }
}

impl SseDecode for crate::plugins::traceroute::TracerouteResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_target = <String>::sse_decode(deserializer);
        let mut var_hops = <Vec<crate::plugins::traceroute::HopStatus>>::sse_decode(deserializer);
        let mut var_aiConclusion = <String>::sse_decode(deserializer);
        return crate::plugins::traceroute::TracerouteResult {
            target: var_target,
            hops: var_hops,
            ai_conclusion: var_aiConclusion,
        };
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::engine::V2Metrics {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_pings = <Vec<crate::plugins::ping::PingStats>>::sse_decode(deserializer);
        let mut var_tcpPingMs = <u32>::sse_decode(deserializer);
        let mut var_gatewayIp = <String>::sse_decode(deserializer);
        let mut var_gatewayPingMs = <u32>::sse_decode(deserializer);
        let mut var_wifi = <Option<crate::plugins::wifi::WifiStats>>::sse_decode(deserializer);
        let mut var_dns = <Vec<crate::plugins::dns::DnsBenchmark>>::sse_decode(deserializer);
        let mut var_downloadSpeed = <f64>::sse_decode(deserializer);
        let mut var_uploadSpeed = <f64>::sse_decode(deserializer);
        let mut var_healthScore = <u32>::sse_decode(deserializer);
        let mut var_healthLabel = <String>::sse_decode(deserializer);
        let mut var_activeConnections = <u32>::sse_decode(deserializer);
        let mut var_adapterSpeedMbps = <u32>::sse_decode(deserializer);
        let mut var_topTraffic =
            <Vec<crate::plugins::traffic::ProcessTraffic>>::sse_decode(deserializer);
        return crate::api::engine::V2Metrics {
            pings: var_pings,
            tcp_ping_ms: var_tcpPingMs,
            gateway_ip: var_gatewayIp,
            gateway_ping_ms: var_gatewayPingMs,
            wifi: var_wifi,
            dns: var_dns,
            download_speed: var_downloadSpeed,
            upload_speed: var_uploadSpeed,
            health_score: var_healthScore,
            health_label: var_healthLabel,
            active_connections: var_activeConnections,
            adapter_speed_mbps: var_adapterSpeedMbps,
            top_traffic: var_topTraffic,
        };
    }
}

impl SseDecode for crate::plugins::wifi::WifiStats {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ssid = <String>::sse_decode(deserializer);
        let mut var_bssid = <String>::sse_decode(deserializer);
        let mut var_signalPct = <u32>::sse_decode(deserializer);
        let mut var_channel = <u16>::sse_decode(deserializer);
        let mut var_frequencyGhz = <f32>::sse_decode(deserializer);
        let mut var_radioType = <String>::sse_decode(deserializer);
        let mut var_authentication = <String>::sse_decode(deserializer);
        let mut var_receiveRateMbps = <u32>::sse_decode(deserializer);
        let mut var_transmitRateMbps = <u32>::sse_decode(deserializer);
        let mut var_band = <String>::sse_decode(deserializer);
        let mut var_retryCount = <u64>::sse_decode(deserializer);
        let mut var_fcsErrorCount = <u64>::sse_decode(deserializer);
        let mut var_transmittedFrames = <u64>::sse_decode(deserializer);
        let mut var_receivedFrames = <u64>::sse_decode(deserializer);
        return crate::plugins::wifi::WifiStats {
            ssid: var_ssid,
            bssid: var_bssid,
            signal_pct: var_signalPct,
            channel: var_channel,
            frequency_ghz: var_frequencyGhz,
            radio_type: var_radioType,
            authentication: var_authentication,
            receive_rate_mbps: var_receiveRateMbps,
            transmit_rate_mbps: var_transmitRateMbps,
            band: var_band,
            retry_count: var_retryCount,
            fcs_error_count: var_fcsErrorCount,
            transmitted_frames: var_transmittedFrames,
            received_frames: var_receivedFrames,
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__ai__analyze_network_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__ai__apply_optimization_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__ai__get_ai_advice_v2_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__ai__get_diagnostics_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__engine__get_v2_metrics_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__ai__run_bufferbloat_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__ai__run_traceroute_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        3 => wire__crate__api__engine__disable_pro_auto_optimize_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__engine__enable_pro_auto_optimize_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__engine__get_about_info_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__engine__init_v2_impl(ptr, rust_vec_len, data_len),
        12 => wire__crate__api__ai__set_api_key_impl(ptr, rust_vec_len, data_len),
        13 => wire__crate__api__engine__start_adaptive_engine_impl(ptr, rust_vec_len, data_len),
        14 => wire__crate__api__engine__stop_adaptive_engine_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::plugins::speedtest::BufferbloatResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.idle_ping_ms.into_into_dart().into_dart(),
            self.download_ping_ms.into_into_dart().into_dart(),
            self.upload_ping_ms.into_into_dart().into_dart(),
            self.grade.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::plugins::speedtest::BufferbloatResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::plugins::speedtest::BufferbloatResult>
    for crate::plugins::speedtest::BufferbloatResult
{
    fn into_into_dart(self) -> crate::plugins::speedtest::BufferbloatResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::plugins::ai::DiagnosticItem {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.severity.into_into_dart().into_dart(),
            self.category.into_into_dart().into_dart(),
            self.problem.into_into_dart().into_dart(),
            self.reason.into_into_dart().into_dart(),
            self.how_checked.into_into_dart().into_dart(),
            self.solution.into_into_dart().into_dart(),
            self.expected_result.into_into_dart().into_dart(),
            self.confidence_pct.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::plugins::ai::DiagnosticItem
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::plugins::ai::DiagnosticItem>
    for crate::plugins::ai::DiagnosticItem
{
    fn into_into_dart(self) -> crate::plugins::ai::DiagnosticItem {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::plugins::dns::DnsBenchmark {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.target.into_into_dart().into_dart(),
            self.latency_ms.into_into_dart().into_dart(),
            self.reliability_pct.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::plugins::dns::DnsBenchmark
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::plugins::dns::DnsBenchmark>
    for crate::plugins::dns::DnsBenchmark
{
    fn into_into_dart(self) -> crate::plugins::dns::DnsBenchmark {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::plugins::traceroute::HopStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.hop.into_into_dart().into_dart(),
            self.ip.into_into_dart().into_dart(),
            self.latency_ms.into_into_dart().into_dart(),
            self.is_timeout.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::plugins::traceroute::HopStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::plugins::traceroute::HopStatus>
    for crate::plugins::traceroute::HopStatus
{
    fn into_into_dart(self) -> crate::plugins::traceroute::HopStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::plugins::optimizer::OptimizationRecommendation {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.description.into_into_dart().into_dart(),
            self.is_recommended.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::plugins::optimizer::OptimizationRecommendation
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::plugins::optimizer::OptimizationRecommendation>
    for crate::plugins::optimizer::OptimizationRecommendation
{
    fn into_into_dart(self) -> crate::plugins::optimizer::OptimizationRecommendation {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::plugins::optimizer::OptimizationReport {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.before_ping.into_into_dart().into_dart(),
            self.after_ping.into_into_dart().into_dart(),
            self.ping_diff.into_into_dart().into_dart(),
            self.summary.into_into_dart().into_dart(),
            self.actions_taken.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::plugins::optimizer::OptimizationReport
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::plugins::optimizer::OptimizationReport>
    for crate::plugins::optimizer::OptimizationReport
{
    fn into_into_dart(self) -> crate::plugins::optimizer::OptimizationReport {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::plugins::ping::PingStats {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.target.into_into_dart().into_dart(),
            self.ping_type.into_into_dart().into_dart(),
            self.average_ms.into_into_dart().into_dart(),
            self.best_ms.into_into_dart().into_dart(),
            self.worst_ms.into_into_dart().into_dart(),
            self.median_ms.into_into_dart().into_dart(),
            self.p95_ms.into_into_dart().into_dart(),
            self.jitter_ms.into_into_dart().into_dart(),
            self.packet_loss_pct.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::plugins::ping::PingStats
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::plugins::ping::PingStats>
    for crate::plugins::ping::PingStats
{
    fn into_into_dart(self) -> crate::plugins::ping::PingStats {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::plugins::traffic::ProcessTraffic {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.pid.into_into_dart().into_dart(),
            self.memory_mb.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::plugins::traffic::ProcessTraffic
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::plugins::traffic::ProcessTraffic>
    for crate::plugins::traffic::ProcessTraffic
{
    fn into_into_dart(self) -> crate::plugins::traffic::ProcessTraffic {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::plugins::traceroute::TracerouteResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.target.into_into_dart().into_dart(),
            self.hops.into_into_dart().into_dart(),
            self.ai_conclusion.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::plugins::traceroute::TracerouteResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::plugins::traceroute::TracerouteResult>
    for crate::plugins::traceroute::TracerouteResult
{
    fn into_into_dart(self) -> crate::plugins::traceroute::TracerouteResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::V2Metrics {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.pings.into_into_dart().into_dart(),
            self.tcp_ping_ms.into_into_dart().into_dart(),
            self.gateway_ip.into_into_dart().into_dart(),
            self.gateway_ping_ms.into_into_dart().into_dart(),
            self.wifi.into_into_dart().into_dart(),
            self.dns.into_into_dart().into_dart(),
            self.download_speed.into_into_dart().into_dart(),
            self.upload_speed.into_into_dart().into_dart(),
            self.health_score.into_into_dart().into_dart(),
            self.health_label.into_into_dart().into_dart(),
            self.active_connections.into_into_dart().into_dart(),
            self.adapter_speed_mbps.into_into_dart().into_dart(),
            self.top_traffic.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::engine::V2Metrics {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::V2Metrics>
    for crate::api::engine::V2Metrics
{
    fn into_into_dart(self) -> crate::api::engine::V2Metrics {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::plugins::wifi::WifiStats {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ssid.into_into_dart().into_dart(),
            self.bssid.into_into_dart().into_dart(),
            self.signal_pct.into_into_dart().into_dart(),
            self.channel.into_into_dart().into_dart(),
            self.frequency_ghz.into_into_dart().into_dart(),
            self.radio_type.into_into_dart().into_dart(),
            self.authentication.into_into_dart().into_dart(),
            self.receive_rate_mbps.into_into_dart().into_dart(),
            self.transmit_rate_mbps.into_into_dart().into_dart(),
            self.band.into_into_dart().into_dart(),
            self.retry_count.into_into_dart().into_dart(),
            self.fcs_error_count.into_into_dart().into_dart(),
            self.transmitted_frames.into_into_dart().into_dart(),
            self.received_frames.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::plugins::wifi::WifiStats
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::plugins::wifi::WifiStats>
    for crate::plugins::wifi::WifiStats
{
    fn into_into_dart(self) -> crate::plugins::wifi::WifiStats {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::plugins::speedtest::BufferbloatResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.idle_ping_ms, serializer);
        <u32>::sse_encode(self.download_ping_ms, serializer);
        <u32>::sse_encode(self.upload_ping_ms, serializer);
        <String>::sse_encode(self.grade, serializer);
    }
}

impl SseEncode for crate::plugins::ai::DiagnosticItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.severity, serializer);
        <String>::sse_encode(self.category, serializer);
        <String>::sse_encode(self.problem, serializer);
        <String>::sse_encode(self.reason, serializer);
        <String>::sse_encode(self.how_checked, serializer);
        <String>::sse_encode(self.solution, serializer);
        <String>::sse_encode(self.expected_result, serializer);
        <u8>::sse_encode(self.confidence_pct, serializer);
    }
}

impl SseEncode for crate::plugins::dns::DnsBenchmark {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.target, serializer);
        <u32>::sse_encode(self.latency_ms, serializer);
        <u8>::sse_encode(self.reliability_pct, serializer);
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::plugins::traceroute::HopStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.hop, serializer);
        <String>::sse_encode(self.ip, serializer);
        <u32>::sse_encode(self.latency_ms, serializer);
        <bool>::sse_encode(self.is_timeout, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::plugins::ai::DiagnosticItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::plugins::ai::DiagnosticItem>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::plugins::dns::DnsBenchmark> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::plugins::dns::DnsBenchmark>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::plugins::traceroute::HopStatus> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::plugins::traceroute::HopStatus>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::plugins::optimizer::OptimizationRecommendation> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::plugins::optimizer::OptimizationRecommendation>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::plugins::ping::PingStats> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::plugins::ping::PingStats>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::plugins::traffic::ProcessTraffic> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::plugins::traffic::ProcessTraffic>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<crate::plugins::wifi::WifiStats> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::plugins::wifi::WifiStats>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::plugins::optimizer::OptimizationRecommendation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.title, serializer);
        <String>::sse_encode(self.description, serializer);
        <bool>::sse_encode(self.is_recommended, serializer);
    }
}

impl SseEncode for crate::plugins::optimizer::OptimizationReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.before_ping, serializer);
        <u32>::sse_encode(self.after_ping, serializer);
        <i32>::sse_encode(self.ping_diff, serializer);
        <String>::sse_encode(self.summary, serializer);
        <Vec<String>>::sse_encode(self.actions_taken, serializer);
    }
}

impl SseEncode for crate::plugins::ping::PingStats {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.target, serializer);
        <String>::sse_encode(self.ping_type, serializer);
        <f32>::sse_encode(self.average_ms, serializer);
        <u32>::sse_encode(self.best_ms, serializer);
        <u32>::sse_encode(self.worst_ms, serializer);
        <u32>::sse_encode(self.median_ms, serializer);
        <u32>::sse_encode(self.p95_ms, serializer);
        <f32>::sse_encode(self.jitter_ms, serializer);
        <f32>::sse_encode(self.packet_loss_pct, serializer);
    }
}

impl SseEncode for crate::plugins::traffic::ProcessTraffic {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <u32>::sse_encode(self.pid, serializer);
        <f64>::sse_encode(self.memory_mb, serializer);
    }
}

impl SseEncode for crate::plugins::traceroute::TracerouteResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.target, serializer);
        <Vec<crate::plugins::traceroute::HopStatus>>::sse_encode(self.hops, serializer);
        <String>::sse_encode(self.ai_conclusion, serializer);
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::engine::V2Metrics {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::plugins::ping::PingStats>>::sse_encode(self.pings, serializer);
        <u32>::sse_encode(self.tcp_ping_ms, serializer);
        <String>::sse_encode(self.gateway_ip, serializer);
        <u32>::sse_encode(self.gateway_ping_ms, serializer);
        <Option<crate::plugins::wifi::WifiStats>>::sse_encode(self.wifi, serializer);
        <Vec<crate::plugins::dns::DnsBenchmark>>::sse_encode(self.dns, serializer);
        <f64>::sse_encode(self.download_speed, serializer);
        <f64>::sse_encode(self.upload_speed, serializer);
        <u32>::sse_encode(self.health_score, serializer);
        <String>::sse_encode(self.health_label, serializer);
        <u32>::sse_encode(self.active_connections, serializer);
        <u32>::sse_encode(self.adapter_speed_mbps, serializer);
        <Vec<crate::plugins::traffic::ProcessTraffic>>::sse_encode(self.top_traffic, serializer);
    }
}

impl SseEncode for crate::plugins::wifi::WifiStats {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.ssid, serializer);
        <String>::sse_encode(self.bssid, serializer);
        <u32>::sse_encode(self.signal_pct, serializer);
        <u16>::sse_encode(self.channel, serializer);
        <f32>::sse_encode(self.frequency_ghz, serializer);
        <String>::sse_encode(self.radio_type, serializer);
        <String>::sse_encode(self.authentication, serializer);
        <u32>::sse_encode(self.receive_rate_mbps, serializer);
        <u32>::sse_encode(self.transmit_rate_mbps, serializer);
        <String>::sse_encode(self.band, serializer);
        <u64>::sse_encode(self.retry_count, serializer);
        <u64>::sse_encode(self.fcs_error_count, serializer);
        <u64>::sse_encode(self.transmitted_frames, serializer);
        <u64>::sse_encode(self.received_frames, serializer);
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
