// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Local AI Diagnostics — no API call needed
class DiagnosticItem {
  final String severity;
  final String category;
  final String problem;
  final String reason;
  final String howChecked;
  final String solution;
  final String expectedResult;
  final int confidencePct;

  const DiagnosticItem({
    required this.severity,
    required this.category,
    required this.problem,
    required this.reason,
    required this.howChecked,
    required this.solution,
    required this.expectedResult,
    required this.confidencePct,
  });

  @override
  int get hashCode =>
      severity.hashCode ^
      category.hashCode ^
      problem.hashCode ^
      reason.hashCode ^
      howChecked.hashCode ^
      solution.hashCode ^
      expectedResult.hashCode ^
      confidencePct.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosticItem &&
          runtimeType == other.runtimeType &&
          severity == other.severity &&
          category == other.category &&
          problem == other.problem &&
          reason == other.reason &&
          howChecked == other.howChecked &&
          solution == other.solution &&
          expectedResult == other.expectedResult &&
          confidencePct == other.confidencePct;
}
