// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class OptimizationRecommendation {
  final String id;
  final String title;
  final String description;
  final bool isRecommended;

  const OptimizationRecommendation({
    required this.id,
    required this.title,
    required this.description,
    required this.isRecommended,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      description.hashCode ^
      isRecommended.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OptimizationRecommendation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          description == other.description &&
          isRecommended == other.isRecommended;
}

class OptimizationReport {
  final int beforePing;
  final int afterPing;
  final int pingDiff;
  final String summary;
  final List<String> actionsTaken;

  const OptimizationReport({
    required this.beforePing,
    required this.afterPing,
    required this.pingDiff,
    required this.summary,
    required this.actionsTaken,
  });

  @override
  int get hashCode =>
      beforePing.hashCode ^
      afterPing.hashCode ^
      pingDiff.hashCode ^
      summary.hashCode ^
      actionsTaken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OptimizationReport &&
          runtimeType == other.runtimeType &&
          beforePing == other.beforePing &&
          afterPing == other.afterPing &&
          pingDiff == other.pingDiff &&
          summary == other.summary &&
          actionsTaken == other.actionsTaken;
}
