// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PingStats {
  final String target;
  final String pingType;
  final double averageMs;
  final int bestMs;
  final int worstMs;
  final int medianMs;
  final int p95Ms;
  final double jitterMs;
  final double packetLossPct;

  const PingStats({
    required this.target,
    required this.pingType,
    required this.averageMs,
    required this.bestMs,
    required this.worstMs,
    required this.medianMs,
    required this.p95Ms,
    required this.jitterMs,
    required this.packetLossPct,
  });

  @override
  int get hashCode =>
      target.hashCode ^
      pingType.hashCode ^
      averageMs.hashCode ^
      bestMs.hashCode ^
      worstMs.hashCode ^
      medianMs.hashCode ^
      p95Ms.hashCode ^
      jitterMs.hashCode ^
      packetLossPct.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PingStats &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          pingType == other.pingType &&
          averageMs == other.averageMs &&
          bestMs == other.bestMs &&
          worstMs == other.worstMs &&
          medianMs == other.medianMs &&
          p95Ms == other.p95Ms &&
          jitterMs == other.jitterMs &&
          packetLossPct == other.packetLossPct;
}
