// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BufferbloatResult {
  final int idlePingMs;
  final int downloadPingMs;
  final int uploadPingMs;
  final String grade;

  const BufferbloatResult({
    required this.idlePingMs,
    required this.downloadPingMs,
    required this.uploadPingMs,
    required this.grade,
  });

  @override
  int get hashCode =>
      idlePingMs.hashCode ^
      downloadPingMs.hashCode ^
      uploadPingMs.hashCode ^
      grade.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BufferbloatResult &&
          runtimeType == other.runtimeType &&
          idlePingMs == other.idlePingMs &&
          downloadPingMs == other.downloadPingMs &&
          uploadPingMs == other.uploadPingMs &&
          grade == other.grade;
}
