// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class HopStatus {
  final int hop;
  final String ip;
  final int latencyMs;
  final bool isTimeout;

  const HopStatus({
    required this.hop,
    required this.ip,
    required this.latencyMs,
    required this.isTimeout,
  });

  @override
  int get hashCode =>
      hop.hashCode ^ ip.hashCode ^ latencyMs.hashCode ^ isTimeout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HopStatus &&
          runtimeType == other.runtimeType &&
          hop == other.hop &&
          ip == other.ip &&
          latencyMs == other.latencyMs &&
          isTimeout == other.isTimeout;
}

class TracerouteResult {
  final String target;
  final List<HopStatus> hops;
  final String aiConclusion;

  const TracerouteResult({
    required this.target,
    required this.hops,
    required this.aiConclusion,
  });

  @override
  int get hashCode => target.hashCode ^ hops.hashCode ^ aiConclusion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TracerouteResult &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          hops == other.hops &&
          aiConclusion == other.aiConclusion;
}
