// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class WifiStats {
  final String ssid;
  final String bssid;
  final int signalPct;
  final int channel;
  final double frequencyGhz;
  final String radioType;
  final String authentication;
  final int receiveRateMbps;
  final int transmitRateMbps;
  final String band;
  final BigInt retryCount;
  final BigInt fcsErrorCount;
  final BigInt transmittedFrames;
  final BigInt receivedFrames;

  const WifiStats({
    required this.ssid,
    required this.bssid,
    required this.signalPct,
    required this.channel,
    required this.frequencyGhz,
    required this.radioType,
    required this.authentication,
    required this.receiveRateMbps,
    required this.transmitRateMbps,
    required this.band,
    required this.retryCount,
    required this.fcsErrorCount,
    required this.transmittedFrames,
    required this.receivedFrames,
  });

  @override
  int get hashCode =>
      ssid.hashCode ^
      bssid.hashCode ^
      signalPct.hashCode ^
      channel.hashCode ^
      frequencyGhz.hashCode ^
      radioType.hashCode ^
      authentication.hashCode ^
      receiveRateMbps.hashCode ^
      transmitRateMbps.hashCode ^
      band.hashCode ^
      retryCount.hashCode ^
      fcsErrorCount.hashCode ^
      transmittedFrames.hashCode ^
      receivedFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WifiStats &&
          runtimeType == other.runtimeType &&
          ssid == other.ssid &&
          bssid == other.bssid &&
          signalPct == other.signalPct &&
          channel == other.channel &&
          frequencyGhz == other.frequencyGhz &&
          radioType == other.radioType &&
          authentication == other.authentication &&
          receiveRateMbps == other.receiveRateMbps &&
          transmitRateMbps == other.transmitRateMbps &&
          band == other.band &&
          retryCount == other.retryCount &&
          fcsErrorCount == other.fcsErrorCount &&
          transmittedFrames == other.transmittedFrames &&
          receivedFrames == other.receivedFrames;
}
