// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ai.dart';
import 'api/engine.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'plugins/ai.dart';
import 'plugins/dns.dart';
import 'plugins/optimizer.dart';
import 'plugins/ping.dart';
import 'plugins/speedtest.dart';
import 'plugins/traceroute.dart';
import 'plugins/traffic.dart';
import 'plugins/wifi.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  WifiStats dco_decode_box_autoadd_wifi_stats(dynamic raw);

  @protected
  BufferbloatResult dco_decode_bufferbloat_result(dynamic raw);

  @protected
  DiagnosticItem dco_decode_diagnostic_item(dynamic raw);

  @protected
  DnsBenchmark dco_decode_dns_benchmark(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  HopStatus dco_decode_hop_status(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DiagnosticItem> dco_decode_list_diagnostic_item(dynamic raw);

  @protected
  List<DnsBenchmark> dco_decode_list_dns_benchmark(dynamic raw);

  @protected
  List<HopStatus> dco_decode_list_hop_status(dynamic raw);

  @protected
  List<OptimizationRecommendation> dco_decode_list_optimization_recommendation(
    dynamic raw,
  );

  @protected
  List<PingStats> dco_decode_list_ping_stats(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProcessTraffic> dco_decode_list_process_traffic(dynamic raw);

  @protected
  WifiStats? dco_decode_opt_box_autoadd_wifi_stats(dynamic raw);

  @protected
  OptimizationRecommendation dco_decode_optimization_recommendation(
    dynamic raw,
  );

  @protected
  OptimizationReport dco_decode_optimization_report(dynamic raw);

  @protected
  PingStats dco_decode_ping_stats(dynamic raw);

  @protected
  ProcessTraffic dco_decode_process_traffic(dynamic raw);

  @protected
  TracerouteResult dco_decode_traceroute_result(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  V2Metrics dco_decode_v_2_metrics(dynamic raw);

  @protected
  WifiStats dco_decode_wifi_stats(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  WifiStats sse_decode_box_autoadd_wifi_stats(SseDeserializer deserializer);

  @protected
  BufferbloatResult sse_decode_bufferbloat_result(SseDeserializer deserializer);

  @protected
  DiagnosticItem sse_decode_diagnostic_item(SseDeserializer deserializer);

  @protected
  DnsBenchmark sse_decode_dns_benchmark(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  HopStatus sse_decode_hop_status(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DiagnosticItem> sse_decode_list_diagnostic_item(
    SseDeserializer deserializer,
  );

  @protected
  List<DnsBenchmark> sse_decode_list_dns_benchmark(
    SseDeserializer deserializer,
  );

  @protected
  List<HopStatus> sse_decode_list_hop_status(SseDeserializer deserializer);

  @protected
  List<OptimizationRecommendation> sse_decode_list_optimization_recommendation(
    SseDeserializer deserializer,
  );

  @protected
  List<PingStats> sse_decode_list_ping_stats(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProcessTraffic> sse_decode_list_process_traffic(
    SseDeserializer deserializer,
  );

  @protected
  WifiStats? sse_decode_opt_box_autoadd_wifi_stats(
    SseDeserializer deserializer,
  );

  @protected
  OptimizationRecommendation sse_decode_optimization_recommendation(
    SseDeserializer deserializer,
  );

  @protected
  OptimizationReport sse_decode_optimization_report(
    SseDeserializer deserializer,
  );

  @protected
  PingStats sse_decode_ping_stats(SseDeserializer deserializer);

  @protected
  ProcessTraffic sse_decode_process_traffic(SseDeserializer deserializer);

  @protected
  TracerouteResult sse_decode_traceroute_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  V2Metrics sse_decode_v_2_metrics(SseDeserializer deserializer);

  @protected
  WifiStats sse_decode_wifi_stats(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_wifi_stats(
    WifiStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bufferbloat_result(
    BufferbloatResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diagnostic_item(
    DiagnosticItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dns_benchmark(DnsBenchmark self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_hop_status(HopStatus self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_diagnostic_item(
    List<DiagnosticItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dns_benchmark(
    List<DnsBenchmark> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_hop_status(
    List<HopStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_optimization_recommendation(
    List<OptimizationRecommendation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ping_stats(
    List<PingStats> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_process_traffic(
    List<ProcessTraffic> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_wifi_stats(
    WifiStats? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_optimization_recommendation(
    OptimizationRecommendation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_optimization_report(
    OptimizationReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ping_stats(PingStats self, SseSerializer serializer);

  @protected
  void sse_encode_process_traffic(
    ProcessTraffic self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_traceroute_result(
    TracerouteResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_v_2_metrics(V2Metrics self, SseSerializer serializer);

  @protected
  void sse_encode_wifi_stats(WifiStats self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
