// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ai.dart';
import 'api/engine.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'plugins/ai.dart';
import 'plugins/dns.dart';
import 'plugins/optimizer.dart';
import 'plugins/ping.dart';
import 'plugins/speedtest.dart';
import 'plugins/traceroute.dart';
import 'plugins/traffic.dart';
import 'plugins/wifi.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 947975424;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_ultranet',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<OptimizationRecommendation>> crateApiAiAnalyzeNetwork();

  Future<OptimizationReport> crateApiAiApplyOptimization({
    required List<String> actions,
    required int beforePing,
  });

  void crateApiEngineDisableProAutoOptimize();

  void crateApiEngineEnableProAutoOptimize();

  String crateApiEngineGetAboutInfo();

  Future<String> crateApiAiGetAiAdviceV2({
    required int icmpPing,
    required int tcpPing,
    required int gatewayPing,
    required String gatewayIp,
    required int jitter,
    required double packetLoss,
    required int dnsMs,
    required String dnsServer,
    required int wifiSignal,
    required int wifiChannel,
    required String wifiBand,
    required int activeConnections,
    required int adapterSpeed,
    required double download,
    required double upload,
    required List<String> backgroundApps,
  });

  Future<List<DiagnosticItem>> crateApiAiGetDiagnostics({
    required int icmpPing,
    required int tcpPing,
    required int gatewayPing,
    required String gatewayIp,
    required int jitter,
    required double packetLoss,
    required int dnsMs,
    required String dnsServer,
    required int wifiSignal,
    required int wifiChannel,
    required String wifiBand,
    required int activeConnections,
    required int adapterSpeed,
    required double download,
    required double upload,
    required List<String> backgroundApps,
  });

  Future<V2Metrics> crateApiEngineGetV2Metrics();

  void crateApiEngineInitV2();

  Future<BufferbloatResult> crateApiAiRunBufferbloat({
    required String target,
    required String url,
  });

  Future<TracerouteResult> crateApiAiRunTraceroute({required String target});

  void crateApiAiSetApiKey({required String key});

  void crateApiEngineStartAdaptiveEngine();

  void crateApiEngineStopAdaptiveEngine();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<OptimizationRecommendation>> crateApiAiAnalyzeNetwork() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_optimization_recommendation,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiAnalyzeNetworkConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiAnalyzeNetworkConstMeta =>
      const TaskConstMeta(debugName: "analyze_network", argNames: []);

  @override
  Future<OptimizationReport> crateApiAiApplyOptimization({
    required List<String> actions,
    required int beforePing,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(actions, serializer);
          sse_encode_u_32(beforePing, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_optimization_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiApplyOptimizationConstMeta,
        argValues: [actions, beforePing],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiApplyOptimizationConstMeta =>
      const TaskConstMeta(
        debugName: "apply_optimization",
        argNames: ["actions", "beforePing"],
      );

  @override
  void crateApiEngineDisableProAutoOptimize() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineDisableProAutoOptimizeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineDisableProAutoOptimizeConstMeta =>
      const TaskConstMeta(debugName: "disable_pro_auto_optimize", argNames: []);

  @override
  void crateApiEngineEnableProAutoOptimize() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEnableProAutoOptimizeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEnableProAutoOptimizeConstMeta =>
      const TaskConstMeta(debugName: "enable_pro_auto_optimize", argNames: []);

  @override
  String crateApiEngineGetAboutInfo() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineGetAboutInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineGetAboutInfoConstMeta =>
      const TaskConstMeta(debugName: "get_about_info", argNames: []);

  @override
  Future<String> crateApiAiGetAiAdviceV2({
    required int icmpPing,
    required int tcpPing,
    required int gatewayPing,
    required String gatewayIp,
    required int jitter,
    required double packetLoss,
    required int dnsMs,
    required String dnsServer,
    required int wifiSignal,
    required int wifiChannel,
    required String wifiBand,
    required int activeConnections,
    required int adapterSpeed,
    required double download,
    required double upload,
    required List<String> backgroundApps,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(icmpPing, serializer);
          sse_encode_u_32(tcpPing, serializer);
          sse_encode_u_32(gatewayPing, serializer);
          sse_encode_String(gatewayIp, serializer);
          sse_encode_u_32(jitter, serializer);
          sse_encode_f_32(packetLoss, serializer);
          sse_encode_u_32(dnsMs, serializer);
          sse_encode_String(dnsServer, serializer);
          sse_encode_u_8(wifiSignal, serializer);
          sse_encode_u_16(wifiChannel, serializer);
          sse_encode_String(wifiBand, serializer);
          sse_encode_u_32(activeConnections, serializer);
          sse_encode_u_32(adapterSpeed, serializer);
          sse_encode_f_64(download, serializer);
          sse_encode_f_64(upload, serializer);
          sse_encode_list_String(backgroundApps, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiGetAiAdviceV2ConstMeta,
        argValues: [
          icmpPing,
          tcpPing,
          gatewayPing,
          gatewayIp,
          jitter,
          packetLoss,
          dnsMs,
          dnsServer,
          wifiSignal,
          wifiChannel,
          wifiBand,
          activeConnections,
          adapterSpeed,
          download,
          upload,
          backgroundApps,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiGetAiAdviceV2ConstMeta => const TaskConstMeta(
    debugName: "get_ai_advice_v2",
    argNames: [
      "icmpPing",
      "tcpPing",
      "gatewayPing",
      "gatewayIp",
      "jitter",
      "packetLoss",
      "dnsMs",
      "dnsServer",
      "wifiSignal",
      "wifiChannel",
      "wifiBand",
      "activeConnections",
      "adapterSpeed",
      "download",
      "upload",
      "backgroundApps",
    ],
  );

  @override
  Future<List<DiagnosticItem>> crateApiAiGetDiagnostics({
    required int icmpPing,
    required int tcpPing,
    required int gatewayPing,
    required String gatewayIp,
    required int jitter,
    required double packetLoss,
    required int dnsMs,
    required String dnsServer,
    required int wifiSignal,
    required int wifiChannel,
    required String wifiBand,
    required int activeConnections,
    required int adapterSpeed,
    required double download,
    required double upload,
    required List<String> backgroundApps,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(icmpPing, serializer);
          sse_encode_u_32(tcpPing, serializer);
          sse_encode_u_32(gatewayPing, serializer);
          sse_encode_String(gatewayIp, serializer);
          sse_encode_u_32(jitter, serializer);
          sse_encode_f_32(packetLoss, serializer);
          sse_encode_u_32(dnsMs, serializer);
          sse_encode_String(dnsServer, serializer);
          sse_encode_u_8(wifiSignal, serializer);
          sse_encode_u_16(wifiChannel, serializer);
          sse_encode_String(wifiBand, serializer);
          sse_encode_u_32(activeConnections, serializer);
          sse_encode_u_32(adapterSpeed, serializer);
          sse_encode_f_64(download, serializer);
          sse_encode_f_64(upload, serializer);
          sse_encode_list_String(backgroundApps, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_diagnostic_item,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiGetDiagnosticsConstMeta,
        argValues: [
          icmpPing,
          tcpPing,
          gatewayPing,
          gatewayIp,
          jitter,
          packetLoss,
          dnsMs,
          dnsServer,
          wifiSignal,
          wifiChannel,
          wifiBand,
          activeConnections,
          adapterSpeed,
          download,
          upload,
          backgroundApps,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiGetDiagnosticsConstMeta => const TaskConstMeta(
    debugName: "get_diagnostics",
    argNames: [
      "icmpPing",
      "tcpPing",
      "gatewayPing",
      "gatewayIp",
      "jitter",
      "packetLoss",
      "dnsMs",
      "dnsServer",
      "wifiSignal",
      "wifiChannel",
      "wifiBand",
      "activeConnections",
      "adapterSpeed",
      "download",
      "upload",
      "backgroundApps",
    ],
  );

  @override
  Future<V2Metrics> crateApiEngineGetV2Metrics() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_v_2_metrics,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineGetV2MetricsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineGetV2MetricsConstMeta =>
      const TaskConstMeta(debugName: "get_v2_metrics", argNames: []);

  @override
  void crateApiEngineInitV2() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineInitV2ConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineInitV2ConstMeta =>
      const TaskConstMeta(debugName: "init_v2", argNames: []);

  @override
  Future<BufferbloatResult> crateApiAiRunBufferbloat({
    required String target,
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(target, serializer);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bufferbloat_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiRunBufferbloatConstMeta,
        argValues: [target, url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiRunBufferbloatConstMeta => const TaskConstMeta(
    debugName: "run_bufferbloat",
    argNames: ["target", "url"],
  );

  @override
  Future<TracerouteResult> crateApiAiRunTraceroute({required String target}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(target, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_traceroute_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiRunTracerouteConstMeta,
        argValues: [target],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiRunTracerouteConstMeta =>
      const TaskConstMeta(debugName: "run_traceroute", argNames: ["target"]);

  @override
  void crateApiAiSetApiKey({required String key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAiSetApiKeyConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAiSetApiKeyConstMeta =>
      const TaskConstMeta(debugName: "set_api_key", argNames: ["key"]);

  @override
  void crateApiEngineStartAdaptiveEngine() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineStartAdaptiveEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineStartAdaptiveEngineConstMeta =>
      const TaskConstMeta(debugName: "start_adaptive_engine", argNames: []);

  @override
  void crateApiEngineStopAdaptiveEngine() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineStopAdaptiveEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineStopAdaptiveEngineConstMeta =>
      const TaskConstMeta(debugName: "stop_adaptive_engine", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  WifiStats dco_decode_box_autoadd_wifi_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_wifi_stats(raw);
  }

  @protected
  BufferbloatResult dco_decode_bufferbloat_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BufferbloatResult(
      idlePingMs: dco_decode_u_32(arr[0]),
      downloadPingMs: dco_decode_u_32(arr[1]),
      uploadPingMs: dco_decode_u_32(arr[2]),
      grade: dco_decode_String(arr[3]),
    );
  }

  @protected
  DiagnosticItem dco_decode_diagnostic_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return DiagnosticItem(
      severity: dco_decode_String(arr[0]),
      category: dco_decode_String(arr[1]),
      problem: dco_decode_String(arr[2]),
      reason: dco_decode_String(arr[3]),
      howChecked: dco_decode_String(arr[4]),
      solution: dco_decode_String(arr[5]),
      expectedResult: dco_decode_String(arr[6]),
      confidencePct: dco_decode_u_8(arr[7]),
    );
  }

  @protected
  DnsBenchmark dco_decode_dns_benchmark(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DnsBenchmark(
      target: dco_decode_String(arr[0]),
      latencyMs: dco_decode_u_32(arr[1]),
      reliabilityPct: dco_decode_u_8(arr[2]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HopStatus dco_decode_hop_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HopStatus(
      hop: dco_decode_u_8(arr[0]),
      ip: dco_decode_String(arr[1]),
      latencyMs: dco_decode_u_32(arr[2]),
      isTimeout: dco_decode_bool(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DiagnosticItem> dco_decode_list_diagnostic_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_diagnostic_item).toList();
  }

  @protected
  List<DnsBenchmark> dco_decode_list_dns_benchmark(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dns_benchmark).toList();
  }

  @protected
  List<HopStatus> dco_decode_list_hop_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_hop_status).toList();
  }

  @protected
  List<OptimizationRecommendation> dco_decode_list_optimization_recommendation(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_optimization_recommendation)
        .toList();
  }

  @protected
  List<PingStats> dco_decode_list_ping_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ping_stats).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProcessTraffic> dco_decode_list_process_traffic(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_process_traffic).toList();
  }

  @protected
  WifiStats? dco_decode_opt_box_autoadd_wifi_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_wifi_stats(raw);
  }

  @protected
  OptimizationRecommendation dco_decode_optimization_recommendation(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return OptimizationRecommendation(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      description: dco_decode_String(arr[2]),
      isRecommended: dco_decode_bool(arr[3]),
    );
  }

  @protected
  OptimizationReport dco_decode_optimization_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return OptimizationReport(
      beforePing: dco_decode_u_32(arr[0]),
      afterPing: dco_decode_u_32(arr[1]),
      pingDiff: dco_decode_i_32(arr[2]),
      summary: dco_decode_String(arr[3]),
      actionsTaken: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  PingStats dco_decode_ping_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return PingStats(
      target: dco_decode_String(arr[0]),
      pingType: dco_decode_String(arr[1]),
      averageMs: dco_decode_f_32(arr[2]),
      bestMs: dco_decode_u_32(arr[3]),
      worstMs: dco_decode_u_32(arr[4]),
      medianMs: dco_decode_u_32(arr[5]),
      p95Ms: dco_decode_u_32(arr[6]),
      jitterMs: dco_decode_f_32(arr[7]),
      packetLossPct: dco_decode_f_32(arr[8]),
    );
  }

  @protected
  ProcessTraffic dco_decode_process_traffic(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProcessTraffic(
      name: dco_decode_String(arr[0]),
      pid: dco_decode_u_32(arr[1]),
      memoryMb: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  TracerouteResult dco_decode_traceroute_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TracerouteResult(
      target: dco_decode_String(arr[0]),
      hops: dco_decode_list_hop_status(arr[1]),
      aiConclusion: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  V2Metrics dco_decode_v_2_metrics(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return V2Metrics(
      pings: dco_decode_list_ping_stats(arr[0]),
      tcpPingMs: dco_decode_u_32(arr[1]),
      gatewayIp: dco_decode_String(arr[2]),
      gatewayPingMs: dco_decode_u_32(arr[3]),
      wifi: dco_decode_opt_box_autoadd_wifi_stats(arr[4]),
      dns: dco_decode_list_dns_benchmark(arr[5]),
      downloadSpeed: dco_decode_f_64(arr[6]),
      uploadSpeed: dco_decode_f_64(arr[7]),
      healthScore: dco_decode_u_32(arr[8]),
      healthLabel: dco_decode_String(arr[9]),
      activeConnections: dco_decode_u_32(arr[10]),
      adapterSpeedMbps: dco_decode_u_32(arr[11]),
      topTraffic: dco_decode_list_process_traffic(arr[12]),
    );
  }

  @protected
  WifiStats dco_decode_wifi_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return WifiStats(
      ssid: dco_decode_String(arr[0]),
      bssid: dco_decode_String(arr[1]),
      signalPct: dco_decode_u_32(arr[2]),
      channel: dco_decode_u_16(arr[3]),
      frequencyGhz: dco_decode_f_32(arr[4]),
      radioType: dco_decode_String(arr[5]),
      authentication: dco_decode_String(arr[6]),
      receiveRateMbps: dco_decode_u_32(arr[7]),
      transmitRateMbps: dco_decode_u_32(arr[8]),
      band: dco_decode_String(arr[9]),
      retryCount: dco_decode_u_64(arr[10]),
      fcsErrorCount: dco_decode_u_64(arr[11]),
      transmittedFrames: dco_decode_u_64(arr[12]),
      receivedFrames: dco_decode_u_64(arr[13]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  WifiStats sse_decode_box_autoadd_wifi_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_wifi_stats(deserializer));
  }

  @protected
  BufferbloatResult sse_decode_bufferbloat_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_idlePingMs = sse_decode_u_32(deserializer);
    var var_downloadPingMs = sse_decode_u_32(deserializer);
    var var_uploadPingMs = sse_decode_u_32(deserializer);
    var var_grade = sse_decode_String(deserializer);
    return BufferbloatResult(
      idlePingMs: var_idlePingMs,
      downloadPingMs: var_downloadPingMs,
      uploadPingMs: var_uploadPingMs,
      grade: var_grade,
    );
  }

  @protected
  DiagnosticItem sse_decode_diagnostic_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_severity = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_problem = sse_decode_String(deserializer);
    var var_reason = sse_decode_String(deserializer);
    var var_howChecked = sse_decode_String(deserializer);
    var var_solution = sse_decode_String(deserializer);
    var var_expectedResult = sse_decode_String(deserializer);
    var var_confidencePct = sse_decode_u_8(deserializer);
    return DiagnosticItem(
      severity: var_severity,
      category: var_category,
      problem: var_problem,
      reason: var_reason,
      howChecked: var_howChecked,
      solution: var_solution,
      expectedResult: var_expectedResult,
      confidencePct: var_confidencePct,
    );
  }

  @protected
  DnsBenchmark sse_decode_dns_benchmark(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_target = sse_decode_String(deserializer);
    var var_latencyMs = sse_decode_u_32(deserializer);
    var var_reliabilityPct = sse_decode_u_8(deserializer);
    return DnsBenchmark(
      target: var_target,
      latencyMs: var_latencyMs,
      reliabilityPct: var_reliabilityPct,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  HopStatus sse_decode_hop_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hop = sse_decode_u_8(deserializer);
    var var_ip = sse_decode_String(deserializer);
    var var_latencyMs = sse_decode_u_32(deserializer);
    var var_isTimeout = sse_decode_bool(deserializer);
    return HopStatus(
      hop: var_hop,
      ip: var_ip,
      latencyMs: var_latencyMs,
      isTimeout: var_isTimeout,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DiagnosticItem> sse_decode_list_diagnostic_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DiagnosticItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_diagnostic_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<DnsBenchmark> sse_decode_list_dns_benchmark(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DnsBenchmark>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dns_benchmark(deserializer));
    }
    return ans_;
  }

  @protected
  List<HopStatus> sse_decode_list_hop_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HopStatus>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_hop_status(deserializer));
    }
    return ans_;
  }

  @protected
  List<OptimizationRecommendation> sse_decode_list_optimization_recommendation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OptimizationRecommendation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_optimization_recommendation(deserializer));
    }
    return ans_;
  }

  @protected
  List<PingStats> sse_decode_list_ping_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PingStats>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ping_stats(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProcessTraffic> sse_decode_list_process_traffic(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProcessTraffic>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_process_traffic(deserializer));
    }
    return ans_;
  }

  @protected
  WifiStats? sse_decode_opt_box_autoadd_wifi_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_wifi_stats(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OptimizationRecommendation sse_decode_optimization_recommendation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_isRecommended = sse_decode_bool(deserializer);
    return OptimizationRecommendation(
      id: var_id,
      title: var_title,
      description: var_description,
      isRecommended: var_isRecommended,
    );
  }

  @protected
  OptimizationReport sse_decode_optimization_report(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_beforePing = sse_decode_u_32(deserializer);
    var var_afterPing = sse_decode_u_32(deserializer);
    var var_pingDiff = sse_decode_i_32(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_actionsTaken = sse_decode_list_String(deserializer);
    return OptimizationReport(
      beforePing: var_beforePing,
      afterPing: var_afterPing,
      pingDiff: var_pingDiff,
      summary: var_summary,
      actionsTaken: var_actionsTaken,
    );
  }

  @protected
  PingStats sse_decode_ping_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_target = sse_decode_String(deserializer);
    var var_pingType = sse_decode_String(deserializer);
    var var_averageMs = sse_decode_f_32(deserializer);
    var var_bestMs = sse_decode_u_32(deserializer);
    var var_worstMs = sse_decode_u_32(deserializer);
    var var_medianMs = sse_decode_u_32(deserializer);
    var var_p95Ms = sse_decode_u_32(deserializer);
    var var_jitterMs = sse_decode_f_32(deserializer);
    var var_packetLossPct = sse_decode_f_32(deserializer);
    return PingStats(
      target: var_target,
      pingType: var_pingType,
      averageMs: var_averageMs,
      bestMs: var_bestMs,
      worstMs: var_worstMs,
      medianMs: var_medianMs,
      p95Ms: var_p95Ms,
      jitterMs: var_jitterMs,
      packetLossPct: var_packetLossPct,
    );
  }

  @protected
  ProcessTraffic sse_decode_process_traffic(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_pid = sse_decode_u_32(deserializer);
    var var_memoryMb = sse_decode_f_64(deserializer);
    return ProcessTraffic(name: var_name, pid: var_pid, memoryMb: var_memoryMb);
  }

  @protected
  TracerouteResult sse_decode_traceroute_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_target = sse_decode_String(deserializer);
    var var_hops = sse_decode_list_hop_status(deserializer);
    var var_aiConclusion = sse_decode_String(deserializer);
    return TracerouteResult(
      target: var_target,
      hops: var_hops,
      aiConclusion: var_aiConclusion,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  V2Metrics sse_decode_v_2_metrics(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pings = sse_decode_list_ping_stats(deserializer);
    var var_tcpPingMs = sse_decode_u_32(deserializer);
    var var_gatewayIp = sse_decode_String(deserializer);
    var var_gatewayPingMs = sse_decode_u_32(deserializer);
    var var_wifi = sse_decode_opt_box_autoadd_wifi_stats(deserializer);
    var var_dns = sse_decode_list_dns_benchmark(deserializer);
    var var_downloadSpeed = sse_decode_f_64(deserializer);
    var var_uploadSpeed = sse_decode_f_64(deserializer);
    var var_healthScore = sse_decode_u_32(deserializer);
    var var_healthLabel = sse_decode_String(deserializer);
    var var_activeConnections = sse_decode_u_32(deserializer);
    var var_adapterSpeedMbps = sse_decode_u_32(deserializer);
    var var_topTraffic = sse_decode_list_process_traffic(deserializer);
    return V2Metrics(
      pings: var_pings,
      tcpPingMs: var_tcpPingMs,
      gatewayIp: var_gatewayIp,
      gatewayPingMs: var_gatewayPingMs,
      wifi: var_wifi,
      dns: var_dns,
      downloadSpeed: var_downloadSpeed,
      uploadSpeed: var_uploadSpeed,
      healthScore: var_healthScore,
      healthLabel: var_healthLabel,
      activeConnections: var_activeConnections,
      adapterSpeedMbps: var_adapterSpeedMbps,
      topTraffic: var_topTraffic,
    );
  }

  @protected
  WifiStats sse_decode_wifi_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ssid = sse_decode_String(deserializer);
    var var_bssid = sse_decode_String(deserializer);
    var var_signalPct = sse_decode_u_32(deserializer);
    var var_channel = sse_decode_u_16(deserializer);
    var var_frequencyGhz = sse_decode_f_32(deserializer);
    var var_radioType = sse_decode_String(deserializer);
    var var_authentication = sse_decode_String(deserializer);
    var var_receiveRateMbps = sse_decode_u_32(deserializer);
    var var_transmitRateMbps = sse_decode_u_32(deserializer);
    var var_band = sse_decode_String(deserializer);
    var var_retryCount = sse_decode_u_64(deserializer);
    var var_fcsErrorCount = sse_decode_u_64(deserializer);
    var var_transmittedFrames = sse_decode_u_64(deserializer);
    var var_receivedFrames = sse_decode_u_64(deserializer);
    return WifiStats(
      ssid: var_ssid,
      bssid: var_bssid,
      signalPct: var_signalPct,
      channel: var_channel,
      frequencyGhz: var_frequencyGhz,
      radioType: var_radioType,
      authentication: var_authentication,
      receiveRateMbps: var_receiveRateMbps,
      transmitRateMbps: var_transmitRateMbps,
      band: var_band,
      retryCount: var_retryCount,
      fcsErrorCount: var_fcsErrorCount,
      transmittedFrames: var_transmittedFrames,
      receivedFrames: var_receivedFrames,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_wifi_stats(
    WifiStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_wifi_stats(self, serializer);
  }

  @protected
  void sse_encode_bufferbloat_result(
    BufferbloatResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.idlePingMs, serializer);
    sse_encode_u_32(self.downloadPingMs, serializer);
    sse_encode_u_32(self.uploadPingMs, serializer);
    sse_encode_String(self.grade, serializer);
  }

  @protected
  void sse_encode_diagnostic_item(
    DiagnosticItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.severity, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_String(self.problem, serializer);
    sse_encode_String(self.reason, serializer);
    sse_encode_String(self.howChecked, serializer);
    sse_encode_String(self.solution, serializer);
    sse_encode_String(self.expectedResult, serializer);
    sse_encode_u_8(self.confidencePct, serializer);
  }

  @protected
  void sse_encode_dns_benchmark(DnsBenchmark self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.target, serializer);
    sse_encode_u_32(self.latencyMs, serializer);
    sse_encode_u_8(self.reliabilityPct, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_hop_status(HopStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.hop, serializer);
    sse_encode_String(self.ip, serializer);
    sse_encode_u_32(self.latencyMs, serializer);
    sse_encode_bool(self.isTimeout, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_diagnostic_item(
    List<DiagnosticItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_diagnostic_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dns_benchmark(
    List<DnsBenchmark> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dns_benchmark(item, serializer);
    }
  }

  @protected
  void sse_encode_list_hop_status(
    List<HopStatus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_hop_status(item, serializer);
    }
  }

  @protected
  void sse_encode_list_optimization_recommendation(
    List<OptimizationRecommendation> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_optimization_recommendation(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ping_stats(
    List<PingStats> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ping_stats(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_process_traffic(
    List<ProcessTraffic> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_process_traffic(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_wifi_stats(
    WifiStats? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_wifi_stats(self, serializer);
    }
  }

  @protected
  void sse_encode_optimization_recommendation(
    OptimizationRecommendation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_bool(self.isRecommended, serializer);
  }

  @protected
  void sse_encode_optimization_report(
    OptimizationReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.beforePing, serializer);
    sse_encode_u_32(self.afterPing, serializer);
    sse_encode_i_32(self.pingDiff, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_list_String(self.actionsTaken, serializer);
  }

  @protected
  void sse_encode_ping_stats(PingStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.target, serializer);
    sse_encode_String(self.pingType, serializer);
    sse_encode_f_32(self.averageMs, serializer);
    sse_encode_u_32(self.bestMs, serializer);
    sse_encode_u_32(self.worstMs, serializer);
    sse_encode_u_32(self.medianMs, serializer);
    sse_encode_u_32(self.p95Ms, serializer);
    sse_encode_f_32(self.jitterMs, serializer);
    sse_encode_f_32(self.packetLossPct, serializer);
  }

  @protected
  void sse_encode_process_traffic(
    ProcessTraffic self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.pid, serializer);
    sse_encode_f_64(self.memoryMb, serializer);
  }

  @protected
  void sse_encode_traceroute_result(
    TracerouteResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.target, serializer);
    sse_encode_list_hop_status(self.hops, serializer);
    sse_encode_String(self.aiConclusion, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_v_2_metrics(V2Metrics self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_ping_stats(self.pings, serializer);
    sse_encode_u_32(self.tcpPingMs, serializer);
    sse_encode_String(self.gatewayIp, serializer);
    sse_encode_u_32(self.gatewayPingMs, serializer);
    sse_encode_opt_box_autoadd_wifi_stats(self.wifi, serializer);
    sse_encode_list_dns_benchmark(self.dns, serializer);
    sse_encode_f_64(self.downloadSpeed, serializer);
    sse_encode_f_64(self.uploadSpeed, serializer);
    sse_encode_u_32(self.healthScore, serializer);
    sse_encode_String(self.healthLabel, serializer);
    sse_encode_u_32(self.activeConnections, serializer);
    sse_encode_u_32(self.adapterSpeedMbps, serializer);
    sse_encode_list_process_traffic(self.topTraffic, serializer);
  }

  @protected
  void sse_encode_wifi_stats(WifiStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ssid, serializer);
    sse_encode_String(self.bssid, serializer);
    sse_encode_u_32(self.signalPct, serializer);
    sse_encode_u_16(self.channel, serializer);
    sse_encode_f_32(self.frequencyGhz, serializer);
    sse_encode_String(self.radioType, serializer);
    sse_encode_String(self.authentication, serializer);
    sse_encode_u_32(self.receiveRateMbps, serializer);
    sse_encode_u_32(self.transmitRateMbps, serializer);
    sse_encode_String(self.band, serializer);
    sse_encode_u_64(self.retryCount, serializer);
    sse_encode_u_64(self.fcsErrorCount, serializer);
    sse_encode_u_64(self.transmittedFrames, serializer);
    sse_encode_u_64(self.receivedFrames, serializer);
  }
}
