// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../plugins/ai.dart';
import '../plugins/optimizer.dart';
import '../plugins/speedtest.dart';
import '../plugins/traceroute.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void setApiKey({required String key}) =>
    RustLib.instance.api.crateApiAiSetApiKey(key: key);

/// Run local AI diagnostics (no API call — instant)
Future<List<DiagnosticItem>> getDiagnostics({
  required int icmpPing,
  required int tcpPing,
  required int gatewayPing,
  required String gatewayIp,
  required int jitter,
  required double packetLoss,
  required int dnsMs,
  required String dnsServer,
  required int wifiSignal,
  required int wifiChannel,
  required String wifiBand,
  required int activeConnections,
  required int adapterSpeed,
  required double download,
  required double upload,
  required List<String> backgroundApps,
}) => RustLib.instance.api.crateApiAiGetDiagnostics(
  icmpPing: icmpPing,
  tcpPing: tcpPing,
  gatewayPing: gatewayPing,
  gatewayIp: gatewayIp,
  jitter: jitter,
  packetLoss: packetLoss,
  dnsMs: dnsMs,
  dnsServer: dnsServer,
  wifiSignal: wifiSignal,
  wifiChannel: wifiChannel,
  wifiBand: wifiBand,
  activeConnections: activeConnections,
  adapterSpeed: adapterSpeed,
  download: download,
  upload: upload,
  backgroundApps: backgroundApps,
);

/// Get Gemini AI advice with full payload
Future<String> getAiAdviceV2({
  required int icmpPing,
  required int tcpPing,
  required int gatewayPing,
  required String gatewayIp,
  required int jitter,
  required double packetLoss,
  required int dnsMs,
  required String dnsServer,
  required int wifiSignal,
  required int wifiChannel,
  required String wifiBand,
  required int activeConnections,
  required int adapterSpeed,
  required double download,
  required double upload,
  required List<String> backgroundApps,
}) => RustLib.instance.api.crateApiAiGetAiAdviceV2(
  icmpPing: icmpPing,
  tcpPing: tcpPing,
  gatewayPing: gatewayPing,
  gatewayIp: gatewayIp,
  jitter: jitter,
  packetLoss: packetLoss,
  dnsMs: dnsMs,
  dnsServer: dnsServer,
  wifiSignal: wifiSignal,
  wifiChannel: wifiChannel,
  wifiBand: wifiBand,
  activeConnections: activeConnections,
  adapterSpeed: adapterSpeed,
  download: download,
  upload: upload,
  backgroundApps: backgroundApps,
);

Future<TracerouteResult> runTraceroute({required String target}) =>
    RustLib.instance.api.crateApiAiRunTraceroute(target: target);

Future<BufferbloatResult> runBufferbloat({
  required String target,
  required String url,
}) => RustLib.instance.api.crateApiAiRunBufferbloat(target: target, url: url);

Future<List<OptimizationRecommendation>> analyzeNetwork() =>
    RustLib.instance.api.crateApiAiAnalyzeNetwork();

Future<OptimizationReport> applyOptimization({
  required List<String> actions,
  required int beforePing,
}) => RustLib.instance.api.crateApiAiApplyOptimization(
  actions: actions,
  beforePing: beforePing,
);
