// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../plugins/dns.dart';
import '../plugins/ping.dart';
import '../plugins/traffic.dart';
import '../plugins/wifi.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AUTO_OPTIMIZE`, `CACHED_GATEWAY`, `LAST_RX`, `LAST_TX`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `deref`, `deref`, `deref`, `fmt`, `initialize`, `initialize`, `initialize`, `initialize`

void initV2() => RustLib.instance.api.crateApiEngineInitV2();

void enableProAutoOptimize() =>
    RustLib.instance.api.crateApiEngineEnableProAutoOptimize();

void disableProAutoOptimize() =>
    RustLib.instance.api.crateApiEngineDisableProAutoOptimize();

void startAdaptiveEngine() =>
    RustLib.instance.api.crateApiEngineStartAdaptiveEngine();

void stopAdaptiveEngine() =>
    RustLib.instance.api.crateApiEngineStopAdaptiveEngine();

String getAboutInfo() => RustLib.instance.api.crateApiEngineGetAboutInfo();

Future<V2Metrics> getV2Metrics() =>
    RustLib.instance.api.crateApiEngineGetV2Metrics();

class V2Metrics {
  final List<PingStats> pings;
  final int tcpPingMs;
  final String gatewayIp;
  final int gatewayPingMs;
  final WifiStats? wifi;
  final List<DnsBenchmark> dns;
  final double downloadSpeed;
  final double uploadSpeed;
  final int healthScore;
  final String healthLabel;
  final int activeConnections;
  final int adapterSpeedMbps;
  final List<ProcessTraffic> topTraffic;

  const V2Metrics({
    required this.pings,
    required this.tcpPingMs,
    required this.gatewayIp,
    required this.gatewayPingMs,
    this.wifi,
    required this.dns,
    required this.downloadSpeed,
    required this.uploadSpeed,
    required this.healthScore,
    required this.healthLabel,
    required this.activeConnections,
    required this.adapterSpeedMbps,
    required this.topTraffic,
  });

  @override
  int get hashCode =>
      pings.hashCode ^
      tcpPingMs.hashCode ^
      gatewayIp.hashCode ^
      gatewayPingMs.hashCode ^
      wifi.hashCode ^
      dns.hashCode ^
      downloadSpeed.hashCode ^
      uploadSpeed.hashCode ^
      healthScore.hashCode ^
      healthLabel.hashCode ^
      activeConnections.hashCode ^
      adapterSpeedMbps.hashCode ^
      topTraffic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is V2Metrics &&
          runtimeType == other.runtimeType &&
          pings == other.pings &&
          tcpPingMs == other.tcpPingMs &&
          gatewayIp == other.gatewayIp &&
          gatewayPingMs == other.gatewayPingMs &&
          wifi == other.wifi &&
          dns == other.dns &&
          downloadSpeed == other.downloadSpeed &&
          uploadSpeed == other.uploadSpeed &&
          healthScore == other.healthScore &&
          healthLabel == other.healthLabel &&
          activeConnections == other.activeConnections &&
          adapterSpeedMbps == other.adapterSpeedMbps &&
          topTraffic == other.topTraffic;
}
