name: Build and Release Windows App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.1)'
        required: true
        default: 'v1.0.6'

env:
  VERSION_TAG: "v1.0.6"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Create config.dart
        shell: bash
        run: echo "const String apiKey = '${{ secrets.API_KEY }}';" > lib/config.dart

      - name: Build Windows
        run: flutter build windows --release

      - name: Build Installer
        run: iscc setup.iss

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: UltraNet AI ${{ env.VERSION_TAG }}
          files: build/windows/installer/UltraNet_Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
